{
 "title": "AWS ECS",
 "tags": [
  "prometheus",
  "opsguru",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "label_values(job)" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({job=\"aws_cloudwatch_$region\"},cluster_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({cluster_name=\"$cluster\", job=\"aws_cloudwatch_$region\"},service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_cpuutilization_average{cluster_name=\"$cluster\",service_name=\"$service\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "CPUUtilization_Average"
    }
   ]
  },
  {
   "title": "MemoryUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_memory_utilization_average{cluster_name=\"$cluster\",service_name=\"$service\"}",
     "legendFormat": "MemoryUtilization_Average"
    }
   ]
  },
  {
   "title": "CPUReservation (cluster $cluster,)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_cpureservation_average{cluster_name=\"$cluster\"}",
     "legendFormat": "CPUReservation_Average"
    }
   ]
  },
  {
   "title": "MemoryReservation (cluster $cluster)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_memory_reservation_average{cluster_name=\"$cluster\"}",
     "legendFormat": "MemoryReservation_Average"
    }
   ]
  }
 ]
}