{
 "title": "AWS ELB Application Load Balancer",
 "description": "Visualize AWS ELB Application Load Balancer metrics",
 "tags": [
  "cloudwatch",
  "opsguru",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "label_values(job)" },
   {
    "name": "targetgroup",
    "label": "TargetGroup",
    "query": "label_values({ job=\"aws_cloudwatch_$region\"},target_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "RequestCount / Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_per_target_sum{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "RequestCount_Sum"
    },
    {
     "expr": "aws_applicationelb_target_response_time_average{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "TargetResponseTime_Average"
    }
   ]
  },
  {
   "title": "HTTPCode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_2_xx_count_sum{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "HTTPCode_Target_2XX_Count_Sum"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_3_xx_count_sum{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "HTTPCode_Target_3XX_Count_Sum"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_4_xx_count_sum{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "HTTPCode_Target_4XX_Count_Sum"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_5_xx_count_sum{target_group=~\".*/$targetgroup/.*\",job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "HTTPCode_Target_5XX_Count_Sum"
    },
    {
     "expr": "sum by (job) (aws_applicationelb_httpcode_elb_4_xx_count_sum{job=\"aws_cloudwatch_$region\"})",
     "legendFormat": "HTTPCode_ELB_4XX_Count_Sum"
    },
    {
     "expr": "sum by (job) (aws_applicationelb_httpcode_elb_5_xx_count_sum{job=\"aws_cloudwatch_$region\"})",
     "legendFormat": "HTTPCode_ELB_5XX_Count_Sum"
    }
   ]
  },
  {
   "title": "ConnectionCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (aws_applicationelb_new_connection_count_sum{job=\"aws_cloudwatch_$region\"})",
     "legendFormat": "NewConnectionCount_Sum"
    },
    {
     "expr": "sum by (job) (aws_applicationelb_active_connection_count_sum{job=\"aws_cloudwatch_$region\"})",
     "legendFormat": "ActiveConnectionCount_Sum"
    }
   ]
  },
  {
   "title": "ConsumedLBCapacityUnits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (aws_applicationelb_consumed_lcus_maximum{job=\"aws_cloudwatch_$region\"})"
    }
   ]
  }
 ]
}