{
 "title": "EC2 Nodes Metrics",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time, name)"
   },
   {
    "name": "instance",
    "query": "label_values(node_boot_time{name=\"$node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Net State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "floor((count(up{name=\"$node\"}))/sum(up{name=\"$node\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu{name=~\"$node\", mode=\"system\"})"
    }
   ]
  },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",name='$node'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',name=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',name=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',name=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',name=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',name=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',name=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',name=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',name=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal{name=~'$node'} - node_memory_MemFree{name=~'$node'} - node_memory_Buffers{name=~'$node'} - node_memory_Cached{name=~'$node'} - node_memory_SwapCached{name=~'$node'} - node_memory_Slab{name=~'$node'} - node_memory_PageTables{name=~'$node'} - node_memory_VmallocUsed{name=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers{name=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{name=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{name=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab{name=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached{name=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables{name=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed{name=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal{name=~'$node'} - node_memory_SwapFree{name=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS{name=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped{name=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active{name=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive{name=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{name=~\"$node\"}",
     "legendFormat": "load1 $instance"
    },
    {
     "expr": "node_load5{name=~\"$node\"}",
     "legendFormat": "load5   $instance"
    },
    {
     "expr": "node_load15{name=~\"$node\"}",
     "legendFormat": "load15   $instance"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_free{name=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{name=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{name=~\"$node\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{name=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{name=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{name=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_sectors_written{name=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{name=~\"$node\"}[5m])",
     "legendFormat": "context switches"
    },
    {
     "expr": "irate(node_intr{name=~\"$node\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{name=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes{name=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{name=~'$node'}",
     "legendFormat": "established"
    },
    {
     "expr": "node_netstat_Tcp_ActiveOpens{name=~'$node'}",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "node_netstat_Tcp_PassiveOpens{name=~'$node'}",
     "legendFormat": "passiveOpens"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{name=~\"$node\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{name=~\"$node\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{name=~\"$node\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{name=~\"$node\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  }
 ]
}