{
 "title": "RDS  Dashboard",
 "description": "Various Metrics Of RDS",
 "tags": [
  "cloudwatch",
  "prometheus"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "DBInstance",
    "label": "DBInstance",
    "query": "label_values(dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "RDS's cpu utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Percentage" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS's connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Connection #" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Free Storage/Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Free Storage"
    },
    {
     "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Read IOPS/Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "aws_rds_write_iops_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Write IOPS"
    },
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=\"$DBInstance\"}/aws_rds_write_iops_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Read/Write Ratio"
    }
   ]
  },
  {
   "title": "Read/Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_latency_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "aws_rds_write_latency_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Connections / Diskqueue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=\"$DBInstance\"}/aws_rds_disk_queue_depth_average{dbinstance_identifier=\"$DBInstance\"}",
     "legendFormat": "Connection/Diskqueue"
    }
   ]
  }
 ]
}