{
 "title": "AWS SES",
 "tags": [
  "prometheus",
  "opsguru",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Send / Delivery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ses_send_average{job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "Send_Average"
    },
    {
     "expr": "aws_ses_delivery_average{job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "Delivery_Average"
    }
   ]
  },
  {
   "title": "Bounce / Reject",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ses_bounce_average{job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "Bounce_Average"
    },
    {
     "expr": "aws_ses_reject_average{job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "Reject_Average"
    }
   ]
  },
  {
   "title": "Complaint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ses_complaint_average{job=\"aws_cloudwatch_$region\"}",
     "legendFormat": "Complaint_Average"
    }
   ]
  }
 ]
}