{
 "title": "AWS SQS",
 "description": "Visualize AWS SQS metrics",
 "tags": [
  "prometheus",
  "cloudwatch",
  "opsguru"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "label_values(job)" },
   {
    "name": "queue",
    "label": "Queue name",
    "query": "label_values({job=\"aws_cloudwatch_$region\"}, queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_deleted_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}\n",
     "legendFormat": "NumberOfMessagesDeleted_Average"
    },
    {
     "expr": "aws_sqs_number_of_empty_receives_average{job=\"aws_cloudwatch_${region}\",queue_name=\"$queue\"}\n",
     "legendFormat": "NumberOfMessagesReceived_Average"
    },
    {
     "expr": "aws_sqs_number_of_messages_sent_average{job=\"aws_cloudwatch_${region}\",queue_name=\"$queue\"}\n",
     "legendFormat": "NumberOfMessagesSent_Average"
    }
   ]
  },
  {
   "title": "ApproximateAgeOfOldestMessage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_deleted_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "ApproximateAgeOfOldestMessage_Average"
    }
   ]
  },
  {
   "title": "ApproximateNumberOfMessages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "ApproximateNumberOfMessagesNotVisible_Average"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "ApproximateNumberOfMessagesDelayed_Average"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "\tApproximateNumberOfMessagesVisible_Average"
    }
   ]
  },
  {
   "title": "NumberOfEmptyReceives",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_empty_receives_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "NumberOfEmptyReceives_Average"
    }
   ]
  },
  {
   "title": "SentMessageSize",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_sent_message_size_average{job=\"aws_cloudwatch_$region\",queue_name=\"$queue\"}",
     "legendFormat": "SentMessageSize_Average"
    }
   ]
  }
 ]
}